"""initial monitoring schema"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    op.create_table("users", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("email", sa.String(320), nullable=False, unique=True), sa.Column("password_hash", sa.String(255), nullable=False), sa.Column("role", sa.String(32), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()))
    op.create_table("competitors", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("name", sa.String(200), nullable=False), sa.Column("website_url", sa.String(2048), nullable=False), sa.Column("blog_url", sa.String(2048)), sa.Column("feed_url", sa.String(2048)), sa.Column("sitemap_url", sa.String(2048)), sa.Column("enabled", sa.Boolean(), nullable=False, server_default=sa.false()), sa.Column("status", sa.String(32), nullable=False, server_default="pending"), sa.Column("last_checked_at", sa.DateTime(timezone=True)), sa.Column("last_successful_detection_at", sa.DateTime(timezone=True)), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()))
    op.create_table("monitoring_configs", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("competitor_id", sa.Integer(), sa.ForeignKey("competitors.id", ondelete="CASCADE"), unique=True), sa.Column("strategy", sa.String(32), nullable=False, server_default="auto"), sa.Column("polling_interval_seconds", sa.Integer(), nullable=False, server_default="300"), sa.Column("timeout_seconds", sa.Integer(), nullable=False, server_default="20"), sa.Column("enabled", sa.Boolean(), nullable=False, server_default=sa.false()), sa.Column("discovered_sources", postgresql.JSONB(), nullable=False, server_default="{}"), sa.Column("discovered_patterns", postgresql.JSONB(), nullable=False, server_default="{}"), sa.Column("configuration_data", postgresql.JSONB(), nullable=False, server_default="{}"), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()))
    op.create_table("monitoring_checks", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("competitor_id", sa.Integer(), sa.ForeignKey("competitors.id", ondelete="CASCADE"), nullable=False), sa.Column("started_at", sa.DateTime(timezone=True), nullable=False), sa.Column("completed_at", sa.DateTime(timezone=True)), sa.Column("duration_ms", sa.Integer()), sa.Column("status", sa.String(32), nullable=False), sa.Column("strategy", sa.String(32), nullable=False), sa.Column("articles_found", sa.Integer(), nullable=False, server_default="0"), sa.Column("new_articles_found", sa.Integer(), nullable=False, server_default="0"), sa.Column("error_message", sa.Text()), sa.Column("retry_count", sa.Integer(), nullable=False, server_default="0"))
    op.create_table("articles", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("competitor_id", sa.Integer(), sa.ForeignKey("competitors.id", ondelete="CASCADE"), nullable=False), sa.Column("title", sa.String(1000), nullable=False), sa.Column("url", sa.String(2048), nullable=False), sa.Column("normalized_url", sa.String(2048), nullable=False), sa.Column("canonical_url", sa.String(2048)), sa.Column("source_url", sa.String(2048), nullable=False), sa.Column("author", sa.String(500)), sa.Column("published_at", sa.DateTime(timezone=True)), sa.Column("modified_at", sa.DateTime(timezone=True)), sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False), sa.Column("detection_delay_seconds", sa.Float()), sa.Column("detection_method", sa.String(32), nullable=False), sa.Column("content", sa.Text()), sa.Column("meta_description", sa.Text()), sa.Column("language", sa.String(20)), sa.Column("categories", postgresql.JSONB(), nullable=False, server_default="[]"), sa.Column("tags", postgresql.JSONB(), nullable=False, server_default="[]"), sa.Column("relevant_links", postgresql.JSONB(), nullable=False, server_default="[]"), sa.Column("structured_metadata", postgresql.JSONB(), nullable=False, server_default="{}"), sa.Column("extraction_status", sa.String(32), nullable=False, server_default="pending"), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()), sa.UniqueConstraint("competitor_id", "normalized_url", name="uq_article_competitor_normalized_url"))
    op.create_table("article_images", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("article_id", sa.Integer(), sa.ForeignKey("articles.id", ondelete="CASCADE"), nullable=False), sa.Column("image_url", sa.String(2048), nullable=False), sa.Column("image_type", sa.String(100)), sa.Column("alt_text", sa.String(1000)), sa.Column("width", sa.Integer()), sa.Column("height", sa.Integer()), sa.Column("position", sa.Integer(), nullable=False, server_default="0"))
    op.create_table("detection_events", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("article_id", sa.Integer(), sa.ForeignKey("articles.id", ondelete="CASCADE"), nullable=False), sa.Column("competitor_id", sa.Integer(), sa.ForeignKey("competitors.id", ondelete="CASCADE"), nullable=False), sa.Column("monitoring_check_id", sa.Integer(), sa.ForeignKey("monitoring_checks.id", ondelete="CASCADE"), nullable=False), sa.Column("detection_method", sa.String(32), nullable=False), sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False), sa.Column("published_at", sa.DateTime(timezone=True)), sa.Column("detection_delay_seconds", sa.Float()), sa.Column("event_status", sa.String(32), nullable=False, server_default="detected"), sa.Column("evidence", postgresql.JSONB(), nullable=False, server_default="{}"), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()))
    op.create_table("notifications", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("article_id", sa.Integer(), sa.ForeignKey("articles.id", ondelete="CASCADE"), nullable=False), sa.Column("type", sa.String(32), nullable=False, server_default="in_app"), sa.Column("status", sa.String(32), nullable=False, server_default="pending"), sa.Column("sent_at", sa.DateTime(timezone=True)), sa.Column("error_message", sa.Text()), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()))
    op.create_table("system_settings", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("key", sa.String(100), nullable=False, unique=True), sa.Column("value", postgresql.JSONB(), nullable=False, server_default="{}"), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now()))

def downgrade():
    for table in ("notifications", "detection_events", "article_images", "articles", "monitoring_checks", "monitoring_configs", "competitors", "users", "system_settings"):
        op.drop_table(table)
